=== tapiwanasheMbizvo/IIB/ZBESBDBLOGGER/importFiles/DFDL_models/Balance_Enquiry_Response.xsd
<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:dfdl="http://www.ogf.org/dfdl/dfdl-1.0/" xmlns:dfdlCobolFmt="http://www.ibm.com/dfdl/CobolDataDefinitionFormat" xmlns:ibmDfdlExtn="http://www.ibm.com/dfdl/extensions" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
  <xsd:import namespace="http://www.ibm.com/dfdl/CobolDataDefinitionFormat" schemaLocation="../../IBMdefined/CobolDataDefinitionFormat.xsd"/>
  <xsd:complexType name="BALANCEENQUIRYRESPONSE">
    <xsd:sequence>
      <xsd:element default=" " dfdl:length="138" name="DUMMY001_138">
        <xsd:annotation>
          <xsd:appinfo source="http://www.wsadie.com/appinfo">
            <initialValue kind="SPACE"/>
          </xsd:appinfo>
          <xsd:documentation>PIC X display</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="dfdlCobolFmt:PICX__string">
            <xsd:maxLength value="1"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element default=" " dfdl:length="15" name="PCREF">
        <xsd:annotation>
          <xsd:appinfo source="http://www.wsadie.com/appinfo">
            <initialValue kind="SPACE"/>
          </xsd:appinfo>
          <xsd:documentation>PIC X(15) display</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="dfdlCobolFmt:PICX__string">
            <xsd:maxLength value="15"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element default=" " dfdl:length="221" name="DUMMY002_221">
        <xsd:annotation>
          <xsd:appinfo source="http://www.wsadie.com/appinfo">
            <initialValue kind="SPACE"/>
          </xsd:appinfo>
          <xsd:documentation>PIC X display</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="dfdlCobolFmt:PICX__string">
            <xsd:maxLength value="1"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element default=" " dfdl:length="16" name="OVERDRAFTLIMIT">
        <xsd:annotation>
          <xsd:appinfo source="http://www.wsadie.com/appinfo">
            <initialValue kind="SPACE"/>
          </xsd:appinfo>
          <xsd:documentation>PIC X(16) display</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="dfdlCobolFmt:PICX__string">
            <xsd:maxLength value="16"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element default=" " dfdl:length="7" name="DUMMY003_007">
        <xsd:annotation>
          <xsd:appinfo source="http://www.wsadie.com/appinfo">
            <initialValue kind="SPACE"/>
          </xsd:appinfo>
          <xsd:documentation>PIC X display</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="dfdlCobolFmt:PICX__string">
            <xsd:maxLength value="1"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element default=" " dfdl:length="1" name="OVERDRAFTEXPIRED">
        <xsd:annotation>
          <xsd:appinfo source="http://www.wsadie.com/appinfo">
            <initialValue kind="SPACE"/>
          </xsd:appinfo>
          <xsd:documentation>PIC X display</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="dfdlCobolFmt:PICX__string">
            <xsd:maxLength value="1"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element default=" " dfdl:length="16" name="RESERVEDBALANCE">
        <xsd:annotation>
          <xsd:appinfo source="http://www.wsadie.com/appinfo">
            <initialValue kind="SPACE"/>
          </xsd:appinfo>
          <xsd:documentation>PIC X(16) display</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="dfdlCobolFmt:PICX__string">
            <xsd:maxLength value="16"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element default=" " dfdl:length="16" name="CLOSINGBALANCE">
        <xsd:annotation>
          <xsd:appinfo source="http://www.wsadie.com/appinfo">
            <initialValue kind="SPACE"/>
          </xsd:appinfo>
          <xsd:documentation>PIC X(16) display</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="dfdlCobolFmt:PICX__string">
            <xsd:maxLength value="16"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element default=" " dfdl:length="16" name="STATUSBAL">
        <xsd:annotation>
          <xsd:appinfo source="http://www.wsadie.com/appinfo">
            <initialValue kind="SPACE"/>
          </xsd:appinfo>
          <xsd:documentation>PIC X(16) display</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="dfdlCobolFmt:PICX__string">
            <xsd:maxLength value="16"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element default=" " dfdl:length="32" name="DUMMY004_032">
        <xsd:annotation>
          <xsd:appinfo source="http://www.wsadie.com/appinfo">
            <initialValue kind="SPACE"/>
          </xsd:appinfo>
          <xsd:documentation>PIC X display</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="dfdlCobolFmt:PICX__string">
            <xsd:maxLength value="1"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element default=" " dfdl:length="16" name="AVAILABLEBALANCE">
        <xsd:annotation>
          <xsd:appinfo source="http://www.wsadie.com/appinfo">
            <initialValue kind="SPACE"/>
          </xsd:appinfo>
          <xsd:documentation>PIC X(16) display</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="dfdlCobolFmt:PICX__string">
            <xsd:maxLength value="16"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element default=" " dfdl:length="100" name="DUMMY005_100">
        <xsd:annotation>
          <xsd:appinfo source="http://www.wsadie.com/appinfo">
            <initialValue kind="SPACE"/>
          </xsd:appinfo>
          <xsd:documentation>PIC X display</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="dfdlCobolFmt:PICX__string">
            <xsd:maxLength value="1"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element default=" " dfdl:length="16" name="SUM1">
        <xsd:annotation>
          <xsd:appinfo source="http://www.wsadie.com/appinfo">
            <initialValue kind="SPACE"/>
          </xsd:appinfo>
          <xsd:documentation>PIC X(16) display</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="dfdlCobolFmt:PICX__string">
            <xsd:maxLength value="16"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element default=" " dfdl:length="16" name="SUM2">
        <xsd:annotation>
          <xsd:appinfo source="http://www.wsadie.com/appinfo">
            <initialValue kind="SPACE"/>
          </xsd:appinfo>
          <xsd:documentation>PIC X(16) display</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="dfdlCobolFmt:PICX__string">
            <xsd:maxLength value="16"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element default=" " dfdl:length="16" name="SHADOWDEBITS">
        <xsd:annotation>
          <xsd:appinfo source="http://www.wsadie.com/appinfo">
            <initialValue kind="SPACE"/>
          </xsd:appinfo>
          <xsd:documentation>PIC X(16) display</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="dfdlCobolFmt:PICX__string">
            <xsd:maxLength value="16"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element default=" " dfdl:length="16" name="SHADOWCREDITS">
        <xsd:annotation>
          <xsd:appinfo source="http://www.wsadie.com/appinfo">
            <initialValue kind="SPACE"/>
          </xsd:appinfo>
          <xsd:documentation>PIC X(16) display</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="dfdlCobolFmt:PICX__string">
            <xsd:maxLength value="16"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element default=" " dfdl:length="98" name="DUMMY006_098">
        <xsd:annotation>
          <xsd:appinfo source="http://www.wsadie.com/appinfo">
            <initialValue kind="SPACE"/>
          </xsd:appinfo>
          <xsd:documentation>PIC X display</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="dfdlCobolFmt:PICX__string">
            <xsd:maxLength value="1"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:annotation>
    <xsd:appinfo source="http://www.ogf.org/dfdl/">
      <dfdl:format binaryFloatRep="{$dfdl:binaryFloatRep}" byteOrder="{$dfdl:byteOrder}" encoding="{$dfdl:encoding}" ignoreCase="yes" leadingSkip="0" occursCountKind="fixed" ref="dfdlCobolFmt:CobolDataFormat" textNumberPadCharacter="0" textStringJustification="left" textStringPadCharacter="%SP;" textZonedSignStyle="asciiStandard" trailingSkip="0"/>
    </xsd:appinfo>
  </xsd:annotation>
  <xsd:annotation>
    <xsd:documentation>
	This XSD was created by importing COBOL copybook.

	Source file:	importFiles\Balance_Enquiry_Response.cpy

	Import options:
		CODEPAGE=ISO-8859-1
		ENDIAN=Little
		EXTENSION_CBL=FP
		EXTENSION_CCP=FP
		EXTENSION_COB=FP
		EXTENSION_CPY=DS
		EXT_DECIMAL_SIGN=ASCII
		FLOATING_POINT_FORMAT=0
		NSYMBOL=NATIONAL
		NUMPROC=PFD
		PLATFORM_SELECTION=0
		QUOTE=DOUBLE
		REMOTE_ENDIAN=Little
		TRUNC=STD
		SCHEMA_TARGET_NAMESPACE_URI=null
		CREATE_DEFAULT_VALUES_FROM_INITIAL_VALUES=true
		CREATE_FACETS_FROM_LEVEL_88_VALUE_CLAUSES=false
		PRESERVE_CASE_IN_VARIABLE_NAMES=true
		CREATE_NULL_VALUES_FOR_FIELDS=false
		NULL_CHARACTER_FOR_STRING=%SP; 
		NULL_CHARACTER_FOR_NUMBER=%#r00; 
		STRING_PADDING_CHARACTER=%SP;
		NUMBER_PADDING_CHARACTER=0
		DEFAULT_FOR_STRING= 
		DEFAULT_FOR_NUMBER=0

</xsd:documentation>
  </xsd:annotation>
  <xsd:element dfdl:lengthKind="implicit" ibmSchExtn:docRoot="true" name="BALANCEENQUIRYRESPONSE" type="BALANCEENQUIRYRESPONSE"/>
</xsd:schema>

=== tapiwanasheMbizvo/IIB/ZBESBDBLOGGER/importFiles/Balance_Enquiry_Response.xml
<?xml version="1.0" encoding="UTF-8"?>
<BALANCEENQUIRYRESPONSE xmlns:tns="http://www.ibm.com/dfdl/CobolDataDefinitionFormat" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../ZB_Enq0001/Balance_Enquiry_Response.xsd">
  <DUMMY001_138> </DUMMY001_138>
  <PCREF> </PCREF>
  <DUMMY002_221> </DUMMY002_221>
  <OVERDRAFTLIMIT> </OVERDRAFTLIMIT>
  <DUMMY003_007> </DUMMY003_007>
  <OVERDRAFTEXPIRED> </OVERDRAFTEXPIRED>
  <RESERVEDBALANCE> </RESERVEDBALANCE>
  <CLOSINGBALANCE> </CLOSINGBALANCE>
  <STATUSBAL> </STATUSBAL>
  <DUMMY004_032> </DUMMY004_032>
  <AVAILABLEBALANCE> </AVAILABLEBALANCE>
  <DUMMY005_100> </DUMMY005_100>
  <SUM1> </SUM1>
  <SUM2> </SUM2>
  <SHADOWDEBITS> </SHADOWDEBITS>
  <SHADOWCREDITS> </SHADOWCREDITS>
  <DUMMY006_098> </DUMMY006_098>
</BALANCEENQUIRYRESPONSE>
